concept string methods minor arrangement
exercism/python pull request #2329
Opened 2021-02-06 14:58 UTC by valentin-p

* Delete the str-method concept which is now string-method
* Improve introduction in exercise and concept
* Add couple unit tests
* Rename the unit test class to PascalCase

2021-02-06 20:05 UTC, BethanyG requested changes
Thank you for this, @valentin-p!  🎉  🌈   Some of these are suggestions, and some are a bit stronger.  Ping me if you have questions or issues.

2021-02-06 21:41 UTC, valentin-p commented on exercises/concept/little-sisters-essay/.docs/instructions.md
> +In this exercise, you are helping your younger sister edit her paper for school. The teacher is looking for correct punctuation, grammar, and excellent choice of words.
Wow, true, but weird. Thanks

2021-02-08 20:28 UTC, valentin-p commented
Part of #2286

2021-02-09 20:34 UTC, BethanyG commented on exercises/concept/little-sisters-essay/.docs/instructions.md
> +In this exercise you are helping your younger sister edit her paper for school. The teacher is looking for correct punctuation, grammar, and excellent choice of words.
```suggestion
In this exercise you are helping your younger sister edit her paper for school. The teacher is looking for correct punctuation, grammar, and excellent word choice.
```

2021-02-09 20:36 UTC, BethanyG commented on exercises/concept/little-sisters-essay/.docs/instructions.md
> +This function should replace all instances of the `old_word` with the `new_word`, and return a new `str` with the updated sentence.
```suggestion
```

2021-02-09 20:37 UTC, BethanyG commented on exercises/concept/little-sisters-essay/.docs/instructions.md
> +To make the paper _even better_, you can replace some of the adjectives with synonyms. Write the function `replace_word_choice()` that takes `sentence`, `old_word`, and `new_word` as parameters.
```suggestion
To make the paper look professional, unnecessary spacing needs to be removed. Implement the function `remove_extra_spaces()` which `sentence` as a parameter, and removes extra whitespace at the beginning and at the end of the sentence. This function should return a `str`.
```

2021-02-09 20:51 UTC, BethanyG commented on exercises/concept/little-sisters-essay/.docs/instructions.md
> +This function should replace all instances of the `old_word` with the `new_word`, and return a new `str` with the updated sentence.
I think this was a mis-cut and paste.

2021-02-09 20:54 UTC, BethanyG commented on exercises/concept/little-sisters-essay/.docs/instructions.md
> +This function should replace all instances of the `old_word` with the `new_word`, and return a new `str` with the updated sentence.
This sentence needs to be removed....it belongs to the task below.

2021-02-09 20:55 UTC, BethanyG commented on exercises/concept/little-sisters-essay/.docs/instructions.md
> +This function should replace all instances of the `old_word` with the `new_word`, and return a new `str` with the updated sentence.
```suggestion
```

2021-02-09 20:55 UTC, BethanyG commented on exercises/concept/little-sisters-essay/.docs/instructions.md
> +This function should replace all instances of the `old_word` with the `new_word`, and return a new `str` with the updated sentence.
This sentence needs to be removed....it belongs to the task below.

2021-02-10 13:33 UTC, BethanyG approved these changes

2021-02-10 13:33 UTC, merged