Update README to warn about Repo Re-org
exercism/python pull request #2345
Opened 2021-02-12 16:57 UTC by BethanyG

Updated readme to remove links to outdated documentation.  Put up request/warning to only PR for issues flagged `[help wanted]`.

2021-02-12 18:30 UTC, iHiD approved these changes

2021-02-13 14:39 UTC, cmccandless requested changes

2021-02-13 14:39 UTC, cmccandless commented on README.md
> +Our WIP V3 documenatation can be found here:  [exercism V3](https://github.com/exercism/docs).
```suggestion
Our WIP V3 documentation can be found here:  [exercism V3](https://github.com/exercism/docs).
```

2021-02-13 16:30 UTC, BethanyG commented
@cmccandless  - Is there an additional change here I need to accept?

2021-02-13 18:14 UTC, cmccandless approved these changes
LGTM

2021-02-13 19:24 UTC, merged