🤖 Add file patterns to config.json
exercism/python pull request #2358
Opened 2021-02-17 15:09 UTC by ErikSchierboom

**⚠ This PR requires you to make a simple change before merging. ⚠**

---

To save maintainers from having to manually specify the `files` key in their exercises' `.meta/config.json` files, we are providing support for track-level patterns. See [this PR](https://github.com/exercism/docs/pull/58) for details.

This PR adds (**purposefully wrong**) file patterns to the `config.json` file. It is up to you, the track maintainers, to change these patterns to their correct value.

You can use the following placeholders:
- `%{kebab_slug}`: the `kebab-case` exercise slug (e.g. `bit-manipulation`)
- `%{snake_slug}`: the `snake_case` exercise slug (e.g. `bit_manipulation`)
- `%{camel_slug}`: the `camelCase` exercise slug (e.g. `bitManipulation`)
- `%{pascal_slug}`: the `PascalCase` exercise slug (e.g. `BitManipulation`)

We will soon update `configlet` to enable it to automatically populate the `.meta/config.json` file's `files` property, at which point we will then batch-PR updates to all tracks that have merged this PR.

## Tracking
https://github.com/exercism/v3-launch/issues/19

2021-02-17 15:36 UTC, cmccandless commented
These patterns will only be used for exercises currently lacking a .meta/config.json, correct?

2021-02-17 15:37 UTC, cmccandless requested changes

2021-02-17 15:37 UTC, cmccandless commented on config.json
> +      "path/to/%{kebab_slug}.ext"
```suggestion
    "solution": [
      "%{snake_slug}.py"
    ],
    "test": [
      "%{snake_slug}_test.py"
    ],
    "example": [
      ".meta/example.py"
    ],
    "exemplar": [
      ".meta/exemplar.py"
```

2021-02-17 15:51 UTC, ErikSchierboom commented
> These patterns will only be used for exercises currently lacking a .meta/config.json, correct?

Well, to be precise: only for missing or empty entries in the `files` property in the  `.meta/config.json` key of exercises.

2021-02-17 16:02 UTC, BethanyG commented
> _Well, to be precise: only for missing or empty entries in the files property in the .meta/config.json key of exercises._
🎉 
..as long as this is only used/intended for filling in missing or "baseline" info for an existing exercise's `.meta/config.json` key, I'm ok with it.  🙂

2021-02-17 16:04 UTC, ErikSchierboom commented
> ..as long as this is only used/intended for filling in missing or "baseline" info for an existing exercise's .meta/config.json key, I'm ok with it.

It is its only purpose

2021-02-17 16:09 UTC, cmccandless commented
We have some exercises (and may have more in the future) that utilize a `test_utils.py` that is required for the test file. For exercises that **do not** use this, what happens if we add `test_utils.py` to the `files.test` pattern here?

2021-02-17 20:17 UTC, ErikSchierboom commented
> We have some exercises (and may have more in the future) that utilize a test_utils.py that is required for the test file. For exercises that do not use this, what happens if we add test_utils.py to the files.test pattern here?

Nothing. We will not overwrite an array that is non-empty.

2021-02-17 21:16 UTC, BethanyG approved these changes
Looks good!  Thank you @ErikSchierboom & @cmccandless.  🌟

2021-02-18 15:06 UTC, cmccandless commented
> Nothing. We will not overwrite an array that is non-empty.

I wasn't asking about overwriting. I'm asking if we can put a second test file pattern in the _track config.json_ that may not be present in every exercise.

2021-02-18 18:24 UTC, ErikSchierboom commented
> I wasn't asking about overwriting. I'm asking if we can put a second test file pattern in the track config.json that may not be present in every exercise.

Yes, it is an array of files and tracks are free to populate them as desired.

2021-03-01 13:58 UTC, BethanyG commented
@cmccandless  - are we good to merge on this?  Plz let me know.  Thanks!

2021-03-01 14:10 UTC, cmccandless approved these changes
Merge it!

2021-03-01 14:52 UTC, merged