[Linting]: Lint practice stub files (7 / 8)
exercism/python pull request #2803
Opened 2021-11-25 08:57 UTC by J08K

Whooop

2021-11-25 08:58 UTC, J08K commented
Yayy, PR bot is fully working.

2021-11-27 18:07 UTC, BethanyG requested changes
Nice work overall!  🌟   ... We just need to make sure that the stub file for `scale generator` is cleaned out.  ;-) .  The other two are suggestions for readability.  Thanks for submitting this!

2021-11-27 18:07 UTC, BethanyG commented on exercises/practice/spiral-matrix/.meta/example.py
> +    matrix = [[0]*size for _ in range(size)]
```suggestion
    matrix = [[0]*size for row in range(size)]
```

2021-11-27 18:07 UTC, BethanyG commented on exercises/practice/spiral-matrix/.meta/example.py
> +    matrix = [[0]*size for _ in range(size)]
I think keeping this as `row` helps clarify what is happening here.

2021-11-28 22:18 UTC, J08K commented on exercises/practice/scale-generator/scale_generator.py
> +        return self.chromatic_scale[index:] + self.chromatic_scale[:index]
Oh whoopsie daisy

2021-11-28 22:19 UTC, BethanyG approved these changes
💜  🌟

2021-11-28 22:28 UTC, merged