Update sets.py
exercism/python pull request #2851
Opened 2022-01-12 19:35 UTC by zepam

Docstring in categorize_dish() and tag_special_ingredients() references categories.py, which doesn't exist.
The correct reference is sets_categories_data.py.
This is an additional update from the 1/9 commit making similar changes in the code.

2022-01-12 19:51 UTC, BethanyG requested changes
Thank you for submitting this!  You know, I did look over the stub and `.meta/exemplar.py` files when you submitted your first PR -- but my brain skipped right over those docstrings!  😱  .  Glad you caught the references.  Could you also change the docstrings on the `.meta/exemplar.py` file as well?  That would be much appreciated.  😄

2022-01-12 21:43 UTC, BethanyG approved these changes
Excellent!  Thank you for your work.  😄

2022-01-12 21:44 UTC, merged

2022-01-18 22:50 UTC, BethanyG commented
@zepam -  😱   _I am so so sorry!_  I forgot that you need to add your GitHub user name to the contributors list for this exercise! [Here](https://github.com/exercism/python/blob/main/exercises/concept/making-the-grade/.meta/config.json) is an example of what that looks like.  You need to add the key, list, and your name to [this](https://github.com/exercism/python/blob/main/exercises/concept/cater-waiter/.meta/config.json) file. 

I would do it for you -- but I want you to also get credit for the PR.  😄 

 Let me know if you have any questions or issues.  Again, apologies for not remembering to do that earlier.  😞

2022-01-19 01:11 UTC, zepam commented
Thanks for thinking of it! I didn't even know I could do that... and now I get another PR. 😄