Gigasecond adding hints and appending instructions
exercism/python pull request #3021
Opened 2022-04-22 21:46 UTC by CodebyKhayla

Issue #3018

2022-04-22 22:53 UTC, BethanyG requested changes
@CodebyKhayla  - I am _delighted_ you submitting a PR!  This is excellent!  I've marked "required changes" only due to the bullet convention and the reflinks.  Everything else is a suggestion - so feel free to disagree or edit what I've put in.  As long as the bullets and reflinks are accepted, I will approve and merge.  🌟

2022-04-22 22:53 UTC, BethanyG commented on exercises/practice/gigasecond/.docs/instructions.append.md
> +
```suggestion
## Dates and Times in Python

This exercise explores objects from Python's `datetime` module:

```

2022-04-22 22:53 UTC, BethanyG commented on exercises/practice/gigasecond/.docs/instructions.append.md
> +[timedelta objects](https://docs.python.org/3.9/library/datetime.html#timedelta-objects)
```suggestion
- [Official Python documentation on the datetime module][datetime]
- [datetime objects][datetime.datetime]
- [timedelta objects][datetime.timedelta]

[datetime]: https://docs.python.org/3.9/library/datetime.html#module-datetime
[datetime.datetime]: https://docs.python.org/3.9/library/datetime.html#datetime.datetime
[datetime.timedelta]: https://docs.python.org/3.9/library/datetime.html#timedelta-objects
```

2022-04-22 22:53 UTC, BethanyG commented on exercises/practice/gigasecond/.docs/hints.md
> +* Your code should parse a datetime object, add a gigasecond's worth of time to it, and then return the result as a datetime object.
```suggestion
-  Your code should parse a datetime object, add a gigasecond's worth of time to it, and then return the result as a datetime object. 
```

2022-04-22 22:53 UTC, BethanyG commented on exercises/practice/gigasecond/.docs/hints.md
> +* If you're having trouble, remember to take a look at the provided test cases under the Tests tab. These will help you figure out what the expected inputs and outputs of your function(s) should be.
```suggestion
- If you're having trouble, remember to take a look at the provided test cases under the Tests tab. These will help you figure out what the expected inputs and outputs of your function(s) should be.
```

2022-04-22 22:53 UTC, BethanyG commented on exercises/practice/gigasecond/.docs/hints.md
> +* If you're having trouble, remember to take a look at the provided test cases under the Tests tab. These will help you figure out what the expected inputs and outputs of your function(s) should be.
veeery small niggle here. Our internal convention is to use `-` for bullets in markdown.  Either `*` or `-` work, we just tend to use `-`.

2022-04-22 22:53 UTC, BethanyG commented on exercises/practice/gigasecond/.docs/instructions.append.md
> +
Thought there should be a little preamble here,  just to focus the student in on the links.

2022-04-22 22:53 UTC, BethanyG commented on exercises/practice/gigasecond/.docs/instructions.append.md
> +[timedelta objects](https://docs.python.org/3.9/library/datetime.html#timedelta-objects)
Added bullets here to separate the links, and added the reflinks at the bottom of the doc.  If this doesn't read well, feel free to revert the bullets.  The reflinks are part of our spec, and won't show to the end user.

2022-04-23 02:34 UTC, CodebyKhayla commented
Thank you so much for all of your help @BethanyG !!! 
I have learned so much even from this experience.

2022-04-23 02:39 UTC, BethanyG approved these changes
(chef's kiss) Tis a thing of beauty!  @CodebyKhayla  - Thank you so much for these.  They go to production .... shortly!  🌟 🌈

2022-04-23 02:40 UTC, merged