Update introduction.md
exercism/python pull request #3064
Opened 2022-05-24 14:49 UTC by JAButenegro

When explaining elif (changes in lines 48, 52 and 54):
x > y doesn't necessarily guarantee x > z directly, therefore first check-in (if) should be x > y and y > z, while second check-in (elif) could be y > z, therefore else would return z > x and z > y
Counterexample: x = 15, y = 10, z = 20. The current program (since x > y) would return "x is greater than y and z", when x >z is not true. The revised code would also evaluate x > z, therefore returning "z is greater than x and y"

2022-05-24 20:58 UTC, BethanyG requested changes
@JAButenegro - Thank you for catching this error and for submitting a PR.  Two requested changes:
1.  Python allows three-way comparison, so we should probably be using that here.
2.  This introduction document displays before the student finishes an exercise, but we also have an `about.md` that displays _after_.  could you also make these changes in that document as well?

Many thanks!  🌈

2022-05-24 20:58 UTC, BethanyG commented on concepts/conditionals/introduction.md
> +if x > y and x > z:
```suggestion
if x > y > z:

```

2022-05-24 20:58 UTC, BethanyG commented on concepts/conditionals/introduction.md
>  elif y > z:
```suggestion
elif y > x > z:

```

2022-05-24 21:20 UTC, JAButenegro commented
Hi @BethanyG, thanks for the feedback! It's actually my first day on GitHub, but I guess the changes you asked me to do to the about.md file has been completed (you might want to check that anyway). 
Thanks also for the amazing work in Exercism! ❤️

2022-05-25 00:13 UTC, BethanyG approved these changes
@JAButenegro I went ahead and accepted the changes to this PR, so you don't have to dig through the help docs (_its a confusing interface_).  🙂   Thanks for submitting this PR! 🌟

2022-05-25 00:14 UTC, merged

2022-05-25 00:17 UTC, JAButenegro commented
Great! Highly appreciated! 💯