Remove Python 2 references from the track
exercism/python pull request #3437
Opened 2023-06-10 01:13 UTC by IsaacG

Remove Python 2 references from any files in the track.

2023-06-12 17:28 UTC, BethanyG commented
@IsaacG - left you a not on Discord, but noting here too (so we have a record).

It is an unqualified PITA, but even blank lines in test files need to go through the templating system, sadly.  So for the following exercises/test files, you'll need to edit the JinJa2 template, then regenerate the test files and check BOTH into the PR.  Otherwise, the CI will complain and/or fail. 

I'd hold `complex-numbers` for its own PR.  Looks like the upstream tests have changed, so we'll need to run configlet, judge which cases we want to keep or omit, and re-do things.  Considering that we recently changed how that exercise works on this track, we probably want to take a hard look at it and make sure that nothing has gone wrong there.

The other exercises that need their template + re-generation are:

- [ ] Binary Search
- [ ] Rational Numbers
- [ ] Robot Simulator
- [ ] Roman Numerals
- [ ] Scale Generator

Option B is to just leave them out, and we can deal with them when the whole re-queueing thing is completed.

2023-06-15 03:34 UTC, BethanyG requested changes
Please remove the test files that only have blank lines removed or added.  They're not really related to Python 2.7 removal, and they are causing the CI to not pass.  

Additionally, those files are going to have to be regenerated once the whole re-queueing issues are resolved, so I'd rather just group or change them then.  Thanks!

2023-06-15 03:34 UTC, BethanyG commented on exercises/practice/binary-search/binary_search_test.py
Can we omit this change?  Its only the removal of lines in the file and isn't related to Python 2.7.

2023-06-15 03:34 UTC, BethanyG commented on exercises/practice/complex-numbers/complex_numbers_test.py
Can we omit this file change as well?  Not related to Python 2.7.

2023-06-15 03:34 UTC, BethanyG commented on exercises/practice/rational-numbers/rational_numbers_test.py
Again, this is only a blank line removal.  Let's omit this file since its not related to the Python 2.7 change.

2023-06-15 03:34 UTC, BethanyG commented on exercises/practice/robot-simulator/robot_simulator_test.py
Omit this as well.

2023-06-15 03:34 UTC, BethanyG commented on exercises/practice/roman-numerals/roman_numerals_test.py
And this one.

2023-06-15 03:34 UTC, BethanyG commented on exercises/practice/scale-generator/scale_generator_test.py
And this one.

2023-06-15 22:54 UTC, IsaacG commented
Whitespace-only test file changes have been reverted. Thanks!

2023-06-15 23:41 UTC, BethanyG commented
Putting this on hold until the issue related #3373 is resolved & pushed.

2023-06-15 23:43 UTC, BethanyG approved these changes
LGTM.

2023-07-14 12:53 UTC, merged