Approaches for Atbash Cipher
exercism/python pull request #3457
Opened 2023-07-12 11:35 UTC by safwansamsudeen

2023-07-15 06:03 UTC, BethanyG requested changes
Hi @safwansamsudeen  - Thanks for submitting this!  Overall, it reads pretty well, but I am going to need to you change all the single letter variable names to something more readable in your code examples -- our track style is no single letter variable names - not even in comprehensions. Thanks for understanding.  🙂

2023-07-15 06:03 UTC, BethanyG commented on exercises/practice/atbash-cipher/.approaches/mono-function/content.md
> +To explain the translation: we use a dict comprehension in which we reverse the ASCII lowercase digits, and enumerate through them - that is, `z` is 0, `y` is 1, and so on.
```suggestion
To explain the translation: we use a `dict` comprehension in which we reverse the ASCII lowercase digits, and enumerate through them - that is, `z` is 0, `y` is 1, and so on. 
```

2023-07-19 13:01 UTC, safwansamsudeen commented
Hey sorry for the delay. Is `i` for index in loops allowed?

2023-07-20 00:10 UTC, BethanyG commented
> Hey sorry for the delay. Is i for index in loops allowed?

Nope.  We are super-duper pendantic/conservative about it.  `index`, `item`, `member`, etc.

2023-07-20 00:11 UTC, BethanyG commented
CI is broken at the moment.  Trying to get it fixed without having to regenerate all the test files again, but I might have to anyways.

2023-07-20 00:58 UTC, safwansamsudeen commented
> Nope. We are super-duper pendantic/conservative about it.
As you wish ;).

I've also added a link to a Programiz article explaining `maketrans`, based on a student request.

2023-07-31 00:59 UTC, safwansamsudeen commented
@BethanyG could we merge?

2023-07-31 15:10 UTC, BethanyG requested changes
There's a couple of places where the variable names were single letters.  Beyond that, looks good.

2023-07-31 15:10 UTC, BethanyG commented on exercises/practice/atbash-cipher/.approaches/introduction.md
> +    return " ".join(res[i:i+5] for i in range(0, len(res), 5))
```suggestion
    return " ".join(res[index:index+5] for index in range(0, len(res), 5))
```

2023-07-31 15:10 UTC, BethanyG commented on exercises/practice/atbash-cipher/.approaches/introduction.md
> +    return res if decode else " ".join(res[i:i+5] for i in range(0, len(res), 5))
```suggestion
    return res if decode else " ".join(res[index:index+5] for index in range(0, len(res), 5))
```

2023-07-31 15:15 UTC, merged